name: Django Build and Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DATABASE_NAME : ${{ secrets.DATABASE_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip3 install -r Django_Blog/requirements.txt

    - name: Run test
      run: | 
        python Django_Blog/manage.py test blog.tests